// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/printer.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LddConsoleDriverPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriverPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LddFileDriverPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriverPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LddNetworkDriverPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriverPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LddPrinterPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinterPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  LddConsoleDriver
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
          dynamic raw);

  @protected
  LddFileDriver
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
          dynamic raw);

  @protected
  LddNetworkDriver
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
          dynamic raw);

  @protected
  LddPrinter
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          dynamic raw);

  @protected
  LddPrinter
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          dynamic raw);

  @protected
  FutureOr<DartBarcodeBuilder> Function()
      dco_decode_DartFn_Inputs__Output_dart_barcode_builder_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<DartGraphicBuilder> Function()
      dco_decode_DartFn_Inputs__Output_dart_graphic_builder_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<DartQrBuilder> Function()
      dco_decode_DartFn_Inputs__Output_dart_qr_builder_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  LddConsoleDriver
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
          dynamic raw);

  @protected
  LddFileDriver
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
          dynamic raw);

  @protected
  LddNetworkDriver
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
          dynamic raw);

  @protected
  LddPrinter
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DartBarcodeFont dco_decode_box_autoadd_dart_barcode_font(dynamic raw);

  @protected
  DartBarcodeSystem dco_decode_box_autoadd_dart_barcode_system(dynamic raw);

  @protected
  DartBarcodeTextPosition dco_decode_box_autoadd_dart_barcode_text_position(
      dynamic raw);

  @protected
  DartGraphicSize dco_decode_box_autoadd_dart_graphic_size(dynamic raw);

  @protected
  DartQrMode dco_decode_box_autoadd_dart_qr_mode(dynamic raw);

  @protected
  LddQrCorrectionLevel dco_decode_box_autoadd_ldd_qr_correction_level(
      dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  DartBarcodeBuilder dco_decode_dart_barcode_builder(dynamic raw);

  @protected
  DartBarcodeFont dco_decode_dart_barcode_font(dynamic raw);

  @protected
  DartBarcodeSystem dco_decode_dart_barcode_system(dynamic raw);

  @protected
  DartBarcodeTextPosition dco_decode_dart_barcode_text_position(dynamic raw);

  @protected
  DartGraphicBuilder dco_decode_dart_graphic_builder(dynamic raw);

  @protected
  DartGraphicSize dco_decode_dart_graphic_size(dynamic raw);

  @protected
  DartQrBuilder dco_decode_dart_qr_builder(dynamic raw);

  @protected
  DartQrMode dco_decode_dart_qr_mode(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LddAlignment dco_decode_ldd_alignment(dynamic raw);

  @protected
  LddFont dco_decode_ldd_font(dynamic raw);

  @protected
  LddQrCorrectionLevel dco_decode_ldd_qr_correction_level(dynamic raw);

  @protected
  LddUnderlineMode dco_decode_ldd_underline_mode(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DartBarcodeFont? dco_decode_opt_box_autoadd_dart_barcode_font(dynamic raw);

  @protected
  DartBarcodeSystem? dco_decode_opt_box_autoadd_dart_barcode_system(
      dynamic raw);

  @protected
  DartBarcodeTextPosition?
      dco_decode_opt_box_autoadd_dart_barcode_text_position(dynamic raw);

  @protected
  DartGraphicSize? dco_decode_opt_box_autoadd_dart_graphic_size(dynamic raw);

  @protected
  DartQrMode? dco_decode_opt_box_autoadd_dart_qr_mode(dynamic raw);

  @protected
  LddQrCorrectionLevel? dco_decode_opt_box_autoadd_ldd_qr_correction_level(
      dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  LddConsoleDriver
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
          SseDeserializer deserializer);

  @protected
  LddFileDriver
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
          SseDeserializer deserializer);

  @protected
  LddNetworkDriver
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
          SseDeserializer deserializer);

  @protected
  LddPrinter
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          SseDeserializer deserializer);

  @protected
  LddPrinter
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  LddConsoleDriver
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
          SseDeserializer deserializer);

  @protected
  LddFileDriver
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
          SseDeserializer deserializer);

  @protected
  LddNetworkDriver
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
          SseDeserializer deserializer);

  @protected
  LddPrinter
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DartBarcodeFont sse_decode_box_autoadd_dart_barcode_font(
      SseDeserializer deserializer);

  @protected
  DartBarcodeSystem sse_decode_box_autoadd_dart_barcode_system(
      SseDeserializer deserializer);

  @protected
  DartBarcodeTextPosition sse_decode_box_autoadd_dart_barcode_text_position(
      SseDeserializer deserializer);

  @protected
  DartGraphicSize sse_decode_box_autoadd_dart_graphic_size(
      SseDeserializer deserializer);

  @protected
  DartQrMode sse_decode_box_autoadd_dart_qr_mode(SseDeserializer deserializer);

  @protected
  LddQrCorrectionLevel sse_decode_box_autoadd_ldd_qr_correction_level(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  DartBarcodeBuilder sse_decode_dart_barcode_builder(
      SseDeserializer deserializer);

  @protected
  DartBarcodeFont sse_decode_dart_barcode_font(SseDeserializer deserializer);

  @protected
  DartBarcodeSystem sse_decode_dart_barcode_system(
      SseDeserializer deserializer);

  @protected
  DartBarcodeTextPosition sse_decode_dart_barcode_text_position(
      SseDeserializer deserializer);

  @protected
  DartGraphicBuilder sse_decode_dart_graphic_builder(
      SseDeserializer deserializer);

  @protected
  DartGraphicSize sse_decode_dart_graphic_size(SseDeserializer deserializer);

  @protected
  DartQrBuilder sse_decode_dart_qr_builder(SseDeserializer deserializer);

  @protected
  DartQrMode sse_decode_dart_qr_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LddAlignment sse_decode_ldd_alignment(SseDeserializer deserializer);

  @protected
  LddFont sse_decode_ldd_font(SseDeserializer deserializer);

  @protected
  LddQrCorrectionLevel sse_decode_ldd_qr_correction_level(
      SseDeserializer deserializer);

  @protected
  LddUnderlineMode sse_decode_ldd_underline_mode(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DartBarcodeFont? sse_decode_opt_box_autoadd_dart_barcode_font(
      SseDeserializer deserializer);

  @protected
  DartBarcodeSystem? sse_decode_opt_box_autoadd_dart_barcode_system(
      SseDeserializer deserializer);

  @protected
  DartBarcodeTextPosition?
      sse_decode_opt_box_autoadd_dart_barcode_text_position(
          SseDeserializer deserializer);

  @protected
  DartGraphicSize? sse_decode_opt_box_autoadd_dart_graphic_size(
      SseDeserializer deserializer);

  @protected
  DartQrMode? sse_decode_opt_box_autoadd_dart_qr_mode(
      SseDeserializer deserializer);

  @protected
  LddQrCorrectionLevel? sse_decode_opt_box_autoadd_ldd_qr_correction_level(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
          LddConsoleDriver self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
          LddFileDriver self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
          LddNetworkDriver self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          LddPrinter self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          LddPrinter self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs__Output_dart_barcode_builder_AnyhowException(
      FutureOr<DartBarcodeBuilder> Function() self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs__Output_dart_graphic_builder_AnyhowException(
      FutureOr<DartGraphicBuilder> Function() self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs__Output_dart_qr_builder_AnyhowException(
      FutureOr<DartQrBuilder> Function() self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
          LddConsoleDriver self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
          LddFileDriver self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
          LddNetworkDriver self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
          LddPrinter self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_barcode_font(
      DartBarcodeFont self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_barcode_system(
      DartBarcodeSystem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_barcode_text_position(
      DartBarcodeTextPosition self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_graphic_size(
      DartGraphicSize self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_qr_mode(
      DartQrMode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ldd_qr_correction_level(
      LddQrCorrectionLevel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_dart_barcode_builder(
      DartBarcodeBuilder self, SseSerializer serializer);

  @protected
  void sse_encode_dart_barcode_font(
      DartBarcodeFont self, SseSerializer serializer);

  @protected
  void sse_encode_dart_barcode_system(
      DartBarcodeSystem self, SseSerializer serializer);

  @protected
  void sse_encode_dart_barcode_text_position(
      DartBarcodeTextPosition self, SseSerializer serializer);

  @protected
  void sse_encode_dart_graphic_builder(
      DartGraphicBuilder self, SseSerializer serializer);

  @protected
  void sse_encode_dart_graphic_size(
      DartGraphicSize self, SseSerializer serializer);

  @protected
  void sse_encode_dart_qr_builder(DartQrBuilder self, SseSerializer serializer);

  @protected
  void sse_encode_dart_qr_mode(DartQrMode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_alignment(LddAlignment self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_font(LddFont self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_qr_correction_level(
      LddQrCorrectionLevel self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_underline_mode(
      LddUnderlineMode self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_barcode_font(
      DartBarcodeFont? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_barcode_system(
      DartBarcodeSystem? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_barcode_text_position(
      DartBarcodeTextPosition? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_graphic_size(
      DartGraphicSize? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_qr_mode(
      DartQrMode? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ldd_qr_correction_level(
      LddQrCorrectionLevel? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriver =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddConsoleDriverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriver =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddFileDriverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriver =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddNetworkDriverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinterPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_dart_esc_pos_driver_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinter =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLddPrinterPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
